chat/urls.py
from django.urls import path
from .views import *

app_name = "chat"

urlpatterns = [
    path("", ChatBoxView.as_view(), name="chat_box"),
    path("student/<uuid:pk>/chat", ChatMessageView.as_view(), name="chat_message"),
]

parent/urls.py
from django.urls import path
from .views import *

app_name = "parent"

urlpatterns = [
    path("dashboard/", ParentDashboardView.as_view(), name="parent_dashboard"),
    path("announcement/", AnnouncementView.as_view(), name="announcement"),
    path("event/", EventView.as_view(), name="event"),
    path("holiday/", HolidayView.as_view(), name="holiday"),
    # path('courses/',CourseView.as_view(),name='courses'),
    # path('courses/<str:c_id>',CourseDetailView.as_view(),name='coursedetail'),
    path("gallery/", GalleryView.as_view(), name="gallery"),
    path("tansporation/driver/",DriverView.as_view(),name="driver"),
    path("tansporation/bus/",BusView.as_view(),name="bus"),
    path("tansporation/route/",RouteView.as_view(),name="route"),
    path("tansporation/stop/",StopView.as_view(),name="stop"),
    path("tansporation/schedule/",ScheduleView.as_view(),name="schedule"),
    path("tansporation/alert/",AlertView.as_view(),name="alert"),
    path("college/fee/",FeeView.as_view(),name="feelist"),
    path("college/payment/",PaymentView.as_view(),name="payment"),
]

school_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


from accounts.views import *
from student.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
    path("parent/", include("parent.urls")),
    path("profile/", include("user_profile.urls")),
    path("chat/", include("chat.urls")),
    path("staff/",include("staff.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parent/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from accounts.models import *
from school_news.models import *
from gallery.models import *
from .mixins import ParentRequiredMixin
from teacher.models import Attendance
from student.services import *
from staff.models import *

class ParentDashboardView(ParentRequiredMixin, View):
    template_name = "parents/dashboard.html"

    def get(self, request, *args, **kwargs):
        student = request.user.parent.student
        attendance_data = DashboardService.get_attendance_data(student)
        context = {
            "student": student,
            "attendance_data": attendance_data,
        }

        return render(request, self.template_name, context)


class AnnouncementView(ParentRequiredMixin, View):
    active_tab = "announcement"
    template_name = "parents/news/announcement.html"

    def get(self, request, *args, **kwargs):
        announcements = Announcement.objects.all()
        context = {"active_tab": self.active_tab, "announcements": announcements}
        return render(request, self.template_name, context)


class EventView(ParentRequiredMixin, View):
    active_tab = "event"
    template_name = "parents/news/events.html"

    def get(self, request, *args, **kwargs):
        events = Event.objects.all()
        context = {"active_tab": self.active_tab, "events": events}
        return render(request, self.template_name, context)


class HolidayView(ParentRequiredMixin, View):
    active_tab = "holiday"
    template_name = "parents/news/holiday.html"

    def get(self, request, *args, **kwargs):
        holidays = Holiday.objects.all()
        context = {"active_tab": self.active_tab, "holidays": holidays}
        return render(request, self.template_name, context)


# class CourseView(LoginRequiredMixin,View):
#     active_tab = "courses"
#     template_name = "teachers/courses/course.html"
#     def get(self,request):
#         try:
#             courses=Course.objects.filter(teacher=request.user.teacher)
#         except:
#             courses=None
#         context={
#             'active_tab':self.active_tab,
#             'courses':courses
#         }
#         return render(request,self.template_name,context)
# class CourseDetailView(LoginRequiredMixin,View):
#     active_tab = "courses"
#     template_name = "teachers/courses/detail.html"
#     def get(self,request,c_id):
#         try:
#             courses=Course.objects.get(id=c_id)
#         except:
#             courses=None
#         context={
#             'active_tab':self.active_tab,
#             'courses':courses
#         }
#         return render(request,self.template_name,context)


class GalleryView(ParentRequiredMixin, View):
    active_tab = "gallery"
    template_name = "parents/gallery/gallery.html"

    def get(self, request):
        gallerys = Gallery.objects.all()
        context = {"active_tab": self.active_tab, "gallerys": gallerys}
        return render(request, self.template_name, context)

class DriverView(ParentRequiredMixin, View):
    active_tab = "driver"
    template_name = "parents/transportation/driver.html"

    def get(self, request):
        drivers = Driver.objects.all()
        context = {"active_tab": self.active_tab, "drivers": drivers}
        return render(request, self.template_name, context)


class BusView(ParentRequiredMixin, View):
    active_tab = "bus"
    template_name = "parents/transportation/bus.html"

    def get(self, request):
        buses = Bus.objects.all()
        context = {"active_tab": self.active_tab, "buses": buses}
        return render(request, self.template_name, context)


class RouteView(ParentRequiredMixin, View):
    active_tab = "route"
    template_name = "parents/transportation/route.html"

    def get(self, request):
        routes = Route.objects.all()
        context = {"active_tab": self.active_tab, "routes": routes}
        return render(request, self.template_name, context)


class StopView(ParentRequiredMixin, View):
    active_tab = "stop"
    template_name = "parents/transportation/stop.html"

    def get(self, request):
        stops = Stop.objects.all()
        context = {"active_tab": self.active_tab, "stops": stops}
        return render(request, self.template_name, context)

    def post(self, request):
        query = request.POST.get("stopquery")
        stops = Stop.objects.filter(stop_name__icontains=query)
        context = {"active_tab": self.active_tab, "stops": stops}
        return render(request, self.template_name, context)


class ScheduleView(ParentRequiredMixin, View):
    active_tab = "schedule"
    template_name = "parents/transportation/schedule.html"

    def get(self, request):
        schedules = Schedule.objects.all()
        context = {"active_tab": self.active_tab, "schedules": schedules}
        return render(request, self.template_name, context)

    def post(self, request):
        query = request.POST.get("schedulequery")
        schedules = Schedule.objects.filter(route__route_name__icontains=query)
        context = {"active_tab": self.active_tab, "schedules": schedules}
        return render(request, self.template_name, context)


class AlertView(ParentRequiredMixin, View):
    active_tab = "alert"
    template_name = "parents/transportation/alert.html"

    def get(self, request):
        alerts = Alert.objects.all()
        context = {"active_tab": self.active_tab, "alerts": alerts}
        return render(request, self.template_name, context)

#college fee
class FeeView(ParentRequiredMixin,View):
    active_tab = "fee"
    template_name = "parents/college_fee/fee.html"
    def get(self,request):
        fees=Fee.objects.all()
        context={
            "active_tab": self.active_tab,
            "fees":fees
        }
        return render(request,self.template_name,context)
class PaymentView(ParentRequiredMixin,View):
    active_tab = "payment"
    template_name = "parents/college_fee/payment_list.html"
    def get(self,request):
        payments=Payment.objects.filter(student=request.user.parent.student)
        context={
            "active_tab": self.active_tab,
            "payments":payments
        }
        return render(request,self.template_name,context)

templates/parents/dashboard.html
{% extends "parents/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'plugins/simple-calendar/simple-calendar.css'%}">
{{ block.super }} 
</style>

{% endblock link %}
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-sub-header">
                        <h3 class="page-title">Welcome {{profile}} !</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                            <li class="breadcrumb-item active">Teacher</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>




        <div class="row">
            <h3 class="page-title"><b>Attendance of {{student}}</b></h3>
            {% for data in attendance_data %}
            <div class="col-xl-2 col-sm-3 col-6 d-flex">
                <div class="card bg-comman w-100">
                    <div class="card-body d-flex flex-column align-items-center"> 
                        <div class="db-info text-center mb-1"> 
                            <h3>{{ data.course_name }}</h3>
                            <h3>{{ data.total_present }}/{{ data.total_classes }}</h3>
                        </div>
                        <div class="col-lg-3 col-md-3 dash-widget1">
                            <div class="circle-bar circle-bar2">
                                <div class="circle-graph2" data-percent="{{ data.attendance_percentage }}">
                                    <b>{{ data.attendance_percentage }}%</b>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            
            
           
            <div class="col-12 col-lg-12 col-xl-15 d-flex">
                <div class="card flex-fill comman-shadow">
                    <div class="card-body">
                        <div id="calendar-doctor" class="calendar-container"></div>
                        
                    </div>
                </div>
            </div>
        </div>

    </div>

    

</div>
{% endblock content %}

templates/parents/sidebar.html
{% extends "base.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}



{% block sidebar %}



<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title">
                    <span>Main Menu</span>
                </li>
                <li class="submenu">
                    <li><a href="{% url 'parent:parent_dashboard' %}"><i class="feather-grid"></i> <span>
                            Parent Dashboard</span> </a></li>
                    
                </li>
                <li class ="{% if active_tab == 'announcement' %}active{% endif %}"><a href="{% url 'parent:announcement' %}"><i class="fas fa-bullhorn"></i><span> Announcement</span></a></li>
                <li class ="{% if active_tab == 'event' %}active {% endif %}"><a href="{% url 'parent:event' %}" ><i class="fas fa-calendar"></i><span> Events</span></a></li>
                <li class ="{% if active_tab == 'holiday' %}active {% endif %}"><a href="{% url 'parent:holiday' %}" ><i class="fas fa-suitcase"></i></i><span> Holiday</span></a></li>
                <li class ="{% if active_tab == 'gallery' %}active{% endif %}"><a href="{% url 'parent:gallery' %}"><i class="fas fa-images"></i>
                    <span> Gallery</span></a></li>
                    <li class="menu-title">
                        <span>Management</span>
                    </li>
                    <li class="submenu">
                        <a href="#"><i class="fa fa-bus"></i><span> Transporation</span> <span
                                    class="menu-arrow"></span></a>
                        <ul>
                            <li><a href="{% url 'parent:driver' %}" class = "{% if active_tab == 'driver' %}active {% endif %}">Driver</a></li>
                            <li><a href="{% url 'parent:bus' %}" class = "{% if active_tab == 'bus' %}active {% endif %}">Bus</a></li>
                            <li><a href="{% url 'parent:route' %}" class = "{% if active_tab == 'route' %}active {% endif %}">Route</a></li>
                            <li><a href="{% url 'parent:stop' %}" class = "{% if active_tab == 'stop' %}active {% endif %}">Stop</a></li>
                            <li><a href="{% url 'parent:schedule' %}" class = "{% if active_tab == 'schedule' %}active {% endif %}">Schedule</a></li>
                            <li><a href="{% url 'parent:alert' %}" class = "{% if active_tab == 'alert' %}active {% endif %}">Alert</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><i class="fas fa-comment-dollar"></i><span>College Fee</span> <span
                                    class="menu-arrow"></span></a>
                        <ul>
                            <li><a href="{% url 'parent:feelist' %}" class = "{% if active_tab == 'fee' %}active {% endif %}">Fee</a></li>
                            <li><a href="{% url 'parent:payment' %}" class = "{% if active_tab == 'payment' %}active {% endif %}">Payment</a></li>
                        </ul>
                    </li>
            </ul>
        </div>
    </div>
</div>

{% block content %}

{% endblock content %}

{% endblock sidebar %}

{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/feather.min.js'%}"></script>
    <script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
    <script src="{% static 'plugins/apexchart/apexcharts.min.js'%}"></script>
    <script src="{% static 'plugins/apexchart/chart-data.js'%}"></script>
    <script src="{% static 'plugins/simple-calendar/jquery.simple-calendar.js'%}"></script>
    <script src="{% static 'js/calander.js'%}"></script>
    <script src="{% static 'js/circle-progress.min.js'%}"></script>
    <script src="{% static 'js/script.js'%}"></script>
{% endblock script %}