chat/urls.py
from django.urls import path
from .views import *

app_name = "chat"

urlpatterns = [
    path("", ChatBoxView.as_view(), name="chat_box"),
    path("student/<uuid:pk>/chat", ChatMessageView.as_view(), name="chat_message"),
]

school_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


from accounts.views import *
from student.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
    path("parent/", include("parent.urls")),
    path("profile/", include("user_profile.urls")),
    path("chat/", include("chat.urls")),
    path("staff/",include("staff.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from .views import *

app_name = "student"

urlpatterns = [
    path("dashboard/", StudentDashboardView.as_view(), name="student_dashboard"),
    path("assignment/", AssignmentView.as_view(), name="student_assignment"),
    path("submission/<str:a_id>/", SubmissionView.as_view(), name="submission"),
    path("submission_list/", SubmissionListView.as_view(), name="submission_list"),
    path(
        "check_assignment/<uuid:pk>",
        CheckSubmittedAssignment.as_view(),
        name="checked_assignment",
    ),
    path("announcement/", AnnouncementView.as_view(), name="announcement"),
    path("event/", EventView.as_view(), name="event"),
    path("holiday/", HolidayView.as_view(), name="holiday"),
    path("courses/", CourseView.as_view(), name="courses"),
    path("courses/<str:c_id>", CourseDetailView.as_view(), name="coursedetail"),
    path("gallery/", GalleryView.as_view(), name="gallery"),
    path("library/books/",libraryBookView.as_view(),name="librarybook"),
    path("library/borrowed/",BorrowedView.as_view(),name="borrowed"),
    path("tansporation/driver/",DriverView.as_view(),name="driver"),
    path("tansporation/bus/",BusView.as_view(),name="bus"),
    path("tansporation/route/",RouteView.as_view(),name="route"),
    path("tansporation/stop/",StopView.as_view(),name="stop"),
    path("tansporation/schedule/",ScheduleView.as_view(),name="schedule"),
    path("tansporation/alert/",AlertView.as_view(),name="alert"),
    path("college/fee/",FeeView.as_view(),name="feelist"),
    path("college/payment/",PaymentView.as_view(),name="payment"),
]

student/models.py
from django.db import models
from common.models import CommonInfo
from teacher.models import *

from django.core.exceptions import ValidationError


class Submit(CommonInfo):
    work = models.ForeignKey(
        Assignment, on_delete=models.CASCADE, related_name="submission"
    )
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    sb_file = models.FileField(
        upload_to="media/",
        validators=[FileExtensionValidator(["pdf", "docx"])],
        null=True,
        blank=True,
    )
    feedback = models.TextField(blank=True)
    checked = models.BooleanField(default=False)

    def clean(self):
        if not self.image and not self.sb_file:
            raise ValidationError("You must upload either an image or a file.")

    class Meta:
        verbose_name = "Submission"

student/forms.py
from django import forms

from .models import Submit


class SubmissionForm(forms.ModelForm):
    course = forms.CharField(label="Course")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
        self.fields["course"].widget.attrs["readonly"] = True

    class Meta:
        model = Submit
        fields = "__all__"
        exclude = ["feedback", "checked", "student"]
        widgets = {
            "work": forms.TextInput(attrs={"readonly": "readonly"}),
        }

    field_order = ["work", "course"]

student/views.py
from datetime import date
from typing import Any

from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages
from common.base_view import BaseView

# from assignment.models import Assignment, Feedback, Submit
from teacher.models import *
from .models import *
from .forms import SubmissionForm
from school_news.models import *
from gallery.models import *
from .mixins import StudentRequiredMixin
from staff.models import *
from .services import *


class StudentDashboardView(StudentRequiredMixin, View):
    template_name = "students/dashboard.html"

    def get(self, request, *args, **kwargs):
        student = request.user.student
        attendance_data = DashboardService.get_attendance_data(student)
        assignment_data = DashboardService.get_assignment_data(student)

        context = {
            "attendance_data": attendance_data,
            "assignment_data": assignment_data,
        }
        return render(request, self.template_name, context)


class AssignmentView(StudentRequiredMixin, BaseView, View):
    template_name = "students/assignment/assignment_view.html"
    active_tab = "assignment_view"
    today_date = date.today()

    def get(self, request, *args, **kwargs):
        try:
            student = request.user.student
            assignments = Assignment.objects.filter(course__grade=student.grade)
        except Student.DoesNotExist:
            messages.error(request, "You don't have permission to access this page")
            return redirect("login")
        context = {
            "active_tab": self.active_tab,
            "assignments": assignments,
            "today_date": self.today_date,
        }
        return render(request, self.template_name, context)


class SubmissionView(StudentRequiredMixin, View):
    template_name = "students/assignment/assignment_submission.html"
    redirect_url = "student:student_assignment"

    def get(self, request, a_id):
        work = get_object_or_404(Assignment, id=a_id)
        student = request.user.student
        print(student.student_userName)
        initial_data = {"work": work.name, "course": work.course.course_name}
        form = SubmissionForm(initial=initial_data)
        return render(request, self.template_name, {"form": form})

    def post(self, request, a_id):
        work = get_object_or_404(Assignment, id=a_id)
        student = request.user.student
        existing_submission = Submit.objects.filter(work=work, student=student).first()

        request.POST = request.POST.copy()
        request.POST["work"] = str(work.id)
        # request.POST["student"] = str(student.id)

        """
        request.POST = request.POST.copy(): This line creates a shallow copy of the request.POST dictionary. This is done to ensure that the original request.POST dictionary remains unchanged. It's generally a good practice when you need to modify the data.
        
        request.POST["work"] = str(work.id): This line updates the "work" key in the request.POST dictionary. It assigns the string representation (str()) of the work.id to the "work" key. This is important because your form is expecting the "work" value to be a UUID, and str(work.id) provides that UUID in string format.
        """

        form = SubmissionForm(request.POST, request.FILES, instance=existing_submission)
        if form.is_valid():
            submission = form.save(commit=False)
            submission.student = student
            # submission.work = str(work.id)
            submission.save()

        else:

            return render(
                request,
                "students/assignment/assignment_submission.html",
                {"form": form},
            )
        return redirect("student:student_assignment")


class SubmissionListView(StudentRequiredMixin, BaseView, ListView):
    model = Submit
    active_tab = "list_submission"

    template_name = "students/assignment/submission_list.html"
    context_object_name = "submits"
    ordering = ["-created_on"]

    def get_queryset(self):
        print("User:", self.request.user)
        if self.request.user.is_authenticated:
            print("Student:", self.request.user.student)
            queryset = Submit.objects.filter(student=self.request.user.student)
            print("Queryset:", queryset)
            return queryset
        return Submit.objects.none()


class CheckSubmittedAssignment(StudentRequiredMixin, DetailView):
    model = Submit
    active_tab = "list_submission"
    template_name = "students/assignment/checked_assignment.html"

    def get(self, request, *args, **kwargs):
        assignment = self.get_object()
        context = {
            "active_tab": self.active_tab,
            "assignment": assignment,
        }
        return render(request, self.template_name, context)


class AnnouncementView(StudentRequiredMixin, View):
    active_tab = "announcement"
    template_name = "students/news/announcement.html"

    def get(self, request, *args, **kwargs):
        announcements = Announcement.objects.all()
        context = {"active_tab": self.active_tab, "announcements": announcements}
        return render(request, self.template_name, context)


class EventView(StudentRequiredMixin, View):
    active_tab = "event"
    template_name = "students/news/events.html"

    def get(self, request, *args, **kwargs):
        events = Event.objects.all()
        context = {"active_tab": self.active_tab, "events": events}
        return render(request, self.template_name, context)


class HolidayView(StudentRequiredMixin, View):
    active_tab = "holiday"
    template_name = "students/news/holiday.html"

    def get(self, request, *args, **kwargs):
        holidays = Holiday.objects.all()
        context = {"active_tab": self.active_tab, "holidays": holidays}
        return render(request, self.template_name, context)


class CourseView(StudentRequiredMixin, View):
    active_tab = "courses"
    template_name = "students/courses/course.html"

    def get(self, request):
        try:
            courses = Course.objects.filter(grade=request.user.student.grade)
        except:
            courses = None
        context = {"active_tab": self.active_tab, "courses": courses}
        return render(request, self.template_name, context)


class CourseDetailView(StudentRequiredMixin, View):
    active_tab = "courses"
    template_name = "students/courses/detail.html"

    def get(self, request, c_id):
        try:
            courses = Course.objects.get(id=c_id)
        except:
            courses = None
        context = {"active_tab": self.active_tab, "courses": courses}
        return render(request, self.template_name, context)


class GalleryView(StudentRequiredMixin, View):
    active_tab = "gallery"
    template_name = "students/gallery/gallery.html"

    def get(self, request):
        gallerys = Gallery.objects.all()
        context = {"active_tab": self.active_tab, "gallerys": gallerys}
        return render(request, self.template_name, context)


class libraryBookView(StudentRequiredMixin, View):
    active_tab = "librarybook"
    template_name = "students/library/booklist.html"

    def get(self, request):
        books = libraryBook.objects.all()
        context = {"active_tab": self.active_tab, "books": books}
        return render(request, self.template_name, context)

    def post(self, request):
        query = request.POST.get("bookquery")
        books = libraryBook.objects.filter(name__icontains=query)
        context = {"active_tab": self.active_tab, "books": books}
        return render(request, self.template_name, context)


class BorrowedView(StudentRequiredMixin, View):
    active_tab = "borrowed"
    template_name = "students/library/borrowedlist.html"

    def get(self, request):
        borrowlist = Borrowing.objects.filter(borrowed_person=request.user.student)
        context = {"active_tab": self.active_tab, "borrowlist": borrowlist}
        return render(request, self.template_name, context)


class DriverView(StudentRequiredMixin, View):
    active_tab = "driver"
    template_name = "students/transportation/driver.html"

    def get(self, request):
        drivers = Driver.objects.all()
        context = {"active_tab": self.active_tab, "drivers": drivers}
        return render(request, self.template_name, context)


class BusView(StudentRequiredMixin, View):
    active_tab = "bus"
    template_name = "students/transportation/bus.html"

    def get(self, request):
        buses = Bus.objects.all()
        context = {"active_tab": self.active_tab, "buses": buses}
        return render(request, self.template_name, context)


class RouteView(StudentRequiredMixin, View):
    active_tab = "route"
    template_name = "students/transportation/route.html"

    def get(self, request):
        routes = Route.objects.all()
        context = {"active_tab": self.active_tab, "routes": routes}
        return render(request, self.template_name, context)


class StopView(StudentRequiredMixin, View):
    active_tab = "stop"
    template_name = "students/transportation/stop.html"

    def get(self, request):
        stops = Stop.objects.all()
        context = {"active_tab": self.active_tab, "stops": stops}
        return render(request, self.template_name, context)

    def post(self, request):
        query = request.POST.get("stopquery")
        stops = Stop.objects.filter(stop_name__icontains=query)
        context = {"active_tab": self.active_tab, "stops": stops}
        return render(request, self.template_name, context)


class ScheduleView(StudentRequiredMixin, View):
    active_tab = "schedule"
    template_name = "students/transportation/schedule.html"

    def get(self, request):
        schedules = Schedule.objects.all()
        context = {"active_tab": self.active_tab, "schedules": schedules}

templates/students/courses/course.html
{% extends "students/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
<link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
    rel="stylesheet">
<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
<link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}

{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Courses</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Courses</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Courses</h3>
                                </div>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table
                                class="table border-0 star-student table-hover table-center mb-0 datatable table-striped">
                                <thead class="student-thread">
                                    <tr>
                                        <th>Course Name</th>
                                        <th>Teacher</th>
                                        <th class="text-end">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if not courses %}
                                        <tr>
                                            <td><h2>None</h2></td>
                                            <td>None</td>
                                            <td>>None</td>
                                        </tr>
                                    {% endif %}
                                    {% for course in courses %}
                                        <tr>
                                            <td>
                                                <h2>
                                                    {{course.course_name}}
                                                </h2>
                                            </td>
                                            <td>{{course.teacher}}</td>
                                            <td class="text-end">
                                                <div class="actions">
                                                    <a href="{% url 'student:coursedetail' course.id %}" class="btn btn-sm bg-success-light">
                                                        <i class="far fa-eye"></i>
                                                    </a>
                                                </div> 
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'js/feather.min.js'%}"></script>
<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/apexcharts.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/chart-data.js'%}"></script>
<script src="{% static 'js/script.js'%}"></script>
{% endblock script %}

templates/students/courses/detail.html
{% extends "students/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
<link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
    rel="stylesheet">
<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
<link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}

{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Courses</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Courses</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Courses Details</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card bg-primary">
                            {% if not courses %}
                            <div class="card-body">
                                <p>Course not Found!!</p>
                            </div>
                            {%else %}
                                <div class="card-body">
                                    <h5 class="card-title">Course:{{courses.course_name}}</h5>
                                    <p class="card-text">{{courses.descriptions}}</p>
                                    <p class="card-text">Grade:<small class="text-body-secondary">{{courses.grade}}c</small></p>
                                    <p class="card-text">Teacher:<small class="text-body-secondary">{{courses.teacher}}</small></p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'js/feather.min.js'%}"></script>
<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/apexcharts.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/chart-data.js'%}"></script>
<script src="{% static 'js/script.js'%}"></script>
{% endblock script %}