chat/urls.py
from django.urls import path
from .views import *

app_name = "chat"

urlpatterns = [
    path("", ChatBoxView.as_view(), name="chat_box"),
    path("student/<uuid:pk>/chat", ChatMessageView.as_view(), name="chat_message"),
]

school_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


from accounts.views import *
from student.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
    path("parent/", include("parent.urls")),
    path("profile/", include("user_profile.urls")),
    path("chat/", include("chat.urls")),
    path("staff/",include("staff.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path
from .views import *

app_name = "teacher"
urlpatterns = [
    path("dashboard/", TeacherDashboardView.as_view(), name="teacher_dashboard"),
    path("add_assignment/", AddAssignmentView.as_view(), name="add_assignment"),
    path(
        "edit_assignment/<uuid:pk>",
        EditAssignmentView.as_view(),
        name="edit_assignment",
    ),
    path("list_assignment/", ListAssignmentView.as_view(), name="list_assignment"),
    path(
        "delete_assignment/<uuid:assignment_id>",
        DeleteAssignmentView.as_view(),
        name="delete_assignment",
    ),
    path("attendance/", AttendanceCreateView.as_view(), name="attendance"),
    path(
        "submitted_assignment/",
        SubmittedAssignment.as_view(),
        name="submitted_assignment",
    ),
    path(
        "submitted_assignment_detail/<uuid:pk>",
        SubmittedAssignmentDetailView.as_view(),
        name="submitted_assignment_detail",
    ),
    path("announcement/", AnnouncementView.as_view(), name="announcement"),
    path("event/", EventView.as_view(), name="event"),
    path("holiday/", HolidayView.as_view(), name="holiday"),
    path("courses/", CourseView.as_view(), name="courses"),
    path("courses/<str:c_id>", CourseDetailView.as_view(), name="coursedetail"),
    path("gallery/", GalleryView.as_view(), name="gallery"),
]

assignment/models.py
from django.db import models
from common.models import CommonInfo
from accounts.models import Student, Course, Grade
from django.core.validators import FileExtensionValidator


# Create your models here.
# class Assignment(CommonInfo):
#     name = models.CharField(max_length=50)
#     description = models.TextField()
#     start = models.DateTimeField(auto_now_add=True)
#     end = models.DateTimeField()
#     image = models.ImageField(null=True, blank=True)
#     hw_file = models.FileField(
#         upload_to="media/",
#         validators=[FileExtensionValidator(["pdf", "docx"])],
#         null=True,
#         blank=True,
#     )
#     course = models.ForeignKey(Course, on_delete=models.CASCADE)
#     grade = models.ForeignKey(Grade, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.name


# class Submit(CommonInfo):
#     work = models.ForeignKey(Assignment, on_delete=models.CASCADE)
#     student = models.ForeignKey(Student, on_delete=models.CASCADE)
#     image = models.ImageField(null=True, blank=True)
#     sb_file = models.FileField(
#         upload_to="media/",
#         validators=[FileExtensionValidator(["pdf", "docx"])],
#         null=True,
#         blank=True,
#     )


# class Feedback(CommonInfo):
#     fk = models.TextField()
#     fk_work = models.ForeignKey(Submit, on_delete=models.CASCADE)

teacher/models.py
from datetime import date
from django.utils import timezone

from django.db import models
from common.models import CommonInfo, attendance_choice
from accounts.models import Teacher, Student, Course, Grade
from django.core.validators import FileExtensionValidator


# Create your models here.
class Assignment(CommonInfo):
    name = models.CharField(max_length=50)
    description = models.TextField()
    start = models.DateField()
    end = models.DateField()
    image = models.ImageField(null=True, blank=True)
    hw_file = models.FileField(
        upload_to="assignment/",
        validators=[FileExtensionValidator(["pdf", "docx"])],
        null=True,
        blank=True,
    )
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    @property
    def is_past_done(self):
        return date.today() > self.end

    def __str__(self):
        return self.name


class Attendance(CommonInfo):
    teacher = models.ForeignKey(
        Teacher, on_delete=models.CASCADE, related_name="attendance"
    )
    course_class = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="attendance"
    )
    present_student = models.ManyToManyField(Student, related_name="attendance")
    date = models.DateField(default=timezone.now)

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = timezone.now().date()
        super().save(*args, **kwargs)

    class Meta:
        unique_together = ("teacher", "course_class", "date")

    def __str__(self):
        return f"{self.date} - {self.teacher} -  {self.course_class}"

teacher/forms.py
from django import forms
from .models import Assignment, Attendance
from common.models import attendance_choice


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ["course", "name", "description", "start", "end", "image", "hw_file"]


class AttendanceForm(forms.ModelForm):
    status = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Attendance
        fields = "__all__"

teacher/views.py
import datetime
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from django.views.generic import View, CreateView, ListView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from accounts.models import *
from .tasks import send_absence_notification_email
from .models import *
from .forms import *
from django.urls import reverse, reverse_lazy
from student.models import Submit
from common.base_view import BaseView
from school_news.models import *
from gallery.models import *
from .mixins import TeacherRequiredMixin
from .services import *

# from celery import shared_task


class TeacherDashboardView(TeacherRequiredMixin, View):
    template_name = "teachers/dashboard.html"

    def get(self, request, *args, **kwargs):
        assignment = DashboardService.get_assignment_submission_status(
            request.user.teacher
        )
        present_students = DashboardService.get_total_present_students(
            request.user.teacher
        )
        for i in present_students:
            print(i)
        context = {
            "assignment": assignment,
            "present": present_students,
        }
        return render(request, self.template_name, context)


class AddAssignmentView(TeacherRequiredMixin, BaseView, CreateView):
    model = Assignment
    form_class = AssignmentForm
    template_name = "teachers/assignment/add_assignment.html"
    success_url = reverse_lazy("teacher:list_assignment")
    active_tab = "add_assignment"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teacher = Teacher.objects.get(teacher_userName=self.request.user)
        course = Course.objects.filter(teacher=teacher)
        context["courses"] = course
        return context

    def form_valid(self, form):
        print("Hello")
        form.instance.teacher = self.request.user.teacher
        print("Form data:", form.data)
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Error creating assignment. Please correct the form."
        )
        print("invalid")
        print("Form data:", form.data)
        print(form.errors)

        return super().form_invalid(form)


class EditAssignmentView(TeacherRequiredMixin, BaseView, UpdateView):
    model = Assignment
    form_class = AssignmentForm
    template_name = "teachers/assignment/edit_assignment.html"
    success_url = reverse_lazy("teacher:list_assignment")
    active_tab = "list_assignment"

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs["initial"]["start"] = self.object.start.strftime("%Y-%m-%d")
    #     kwargs["initial"]["end"] = self.object.end.strftime("%Y-%m-%d")
    #     return kwargs
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teacher = Teacher.objects.get(teacher_userName=self.request.user)
        course = Course.objects.filter(teacher=teacher)
        context["courses"] = course
        return context

    def get_initial(self):
        initial = super().get_initial()
        assignment = self.get_object()
        # initial["start"] = assignment.start.strftime("%Y-%m-%d")
        # initial["end"] = assignment.end.strftime("%Y-%m-%d")
        initial["image"] = assignment.image
        initial["hw_file"] = assignment.hw_file
        return initial

    def form_valid(self, form):
        form.instance.teacher = self.request.user.teacher
        print("Form data:", form.data)
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Error creating assignment. Please correct the form."
        )
        print("invalid")
        print("Form data:", form.data)
        print(form.errors)

        return super().form_invalid(form)


class ListAssignmentView(TeacherRequiredMixin, BaseView, ListView):
    model = Assignment
    active_tab = "list_assignment"

    template_name = "teachers/assignment/list_assignment.html"
    context_object_name = "assignments"
    ordering = ["-created_on"]

    def get_queryset(self):
        return Assignment.objects.filter(teacher=self.request.user.teacher)


# class DeleteAssignmentView(LoginRequiredMixin, DeleteView):
#     model = Assignment
#     template_name = "teachers/assignment/delete_assignment.html"
#     success_url = reverse_lazy("list_assignment")


class DeleteAssignmentView(View, TeacherRequiredMixin):
    def get(self, request, assignment_id):
        assignment = get_object_or_404(Assignment, id=assignment_id)
        assignment.delete()
        return redirect("teacher:list_assignment")


class AttendanceCreateView(TeacherRequiredMixin, View):
    template_name = "teachers/attendance/attendance_form.html"
    success_url = reverse_lazy("teacher:list_assignment")

    def get_context_data(self, **kwargs):
        context = {}
        # To
        # display
        # student and parent detail of absent student

        # courseName = Course.objects.get(pk="70cde64ee0f942d28cf516cee467b086")
        # print(courseName)
        # studentList = courseName.grade.student.all()
        # print(studentList)
        # student_list = Student.objects.filter(
        #     grade_id="4de24a916f0445eea90c426ef67d9ad1"
        # )
        # print(student_list)

        # # query for present student list
        # attendanceList = Attendance.objects.get(
        #     id="874b8ea2bc93410688cd36efd3df35c5"
        # ).present_student.all()
        # for i in attendanceList:
        #     print(i)
        # print(f"Attendance: {attendanceList}")

        # # Query for absent student
        # # using set to find absent student
        # absent_student = list(set(student_list) - set(attendanceList))

        # # using list comprehension to find absent student
        # # absent_student = [
        # #     student for student in student_list if student not in attendanceList
        # # ]
        # print(f"absent student: {absent_student}")

        # # query to get parent email
        # for i in absent_student:
        #     print(i.parent.email)
        #     print(i.parent)

        # # To
        # # display
        # # student and parent detail of absent student
        # english_class_attendance = Attendance.objects.filter(
        #     course_class_id="70cde64ee0f942d28cf516cee467b086"
        # )
        # print(f" Total days: {len(english_class_attendance)}")
        # student_count = 0
        # for i in english_class_attendance:
        #     if i.present_student.filter(name="Anish Bista").exists():
        #         student_count += 1
        #         print("Present")
        #     print(i.present_student.all())
        # print(f"Anish is present for {student_count}")

        # # To
        # # display
        # # how many days student presents in class

        teacher = Teacher.objects.get(teacher_userName=self.request.user)
        course = Course.objects.filter(teacher=teacher)
        request = self.request
        course_id = request.GET.get("course_id")
        print(f"Course_id:{course_id}")
        if course_id:
            course_object = Course.objects.get(pk=course_id)
            students = course_object.grade.student.all()
            context["students"] = students
        context["courses"] = course
        context["active_tab"] = "attendance_take"
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        course_id = request.POST.get("course_id")
        if not course_id:
            return redirect(reverse("teacher:attendance"))
        course_object = Course.objects.get(pk=course_id)

        teacher = Teacher.objects.get(teacher_userName=self.request.user)

        date = datetime.date.today()

        present_student_ids = request.POST.getlist("present")

        attendance, created = Attendance.objects.get_or_create(
            teacher=teacher, course_class=course_object, date=date
        )

        if not created:
            messages.error(
                request,
                "Attendance already taken for the day!!",
            )
            return redirect(reverse("teacher:attendance"))

        all_students = Student.objects.filter(grade=course_object.grade)
        # print(f"All student list: {all_students}")
        absent_students = all_students.exclude(
            id__in=present_student_ids
        )  # __in lookup is used to filter querysets based on whether a particular field's value is contained within a given list of values. This is useful when you want to retrieve objects where a certain field matches any of the values in a list.
        # print(f"Absent student list: {absent_students}")

        for student in absent_students:
            absent_student_email = student.parent.email
            course_name = course_object.course_name
            teacher_name = teacher.name
            send_absence_notification_email.delay(
                absent_student_email, course_name, teacher_name
            )

        attendance.present_student.set(
            present_student_ids
        )  # In Django's ORM (Object-Relational Mapping), when dealing with a ManyToManyField, you can use the set() method to set the related objects

        return redirect(self.success_url)


class SubmittedAssignment(TeacherRequiredMixin, BaseView, ListView):
    template_name = "teachers/assignment/submitted_assignment.html"
    context_object_name = "assignments"
    active_tab = "submitted_assignment"

    def get_queryset(self):
        return Submit.objects.filter(work__teacher=self.request.user.teacher)

templates/teachers/assignment/delete_assignment.html
 <h2>Confirm Deletion</h2>
    <p>Are you sure you want to delete this assignment?</p>
    <form method="post" action="">
        {% csrf_token %}
        <p>Are you sure you want to delete?</p>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>

templates/teachers/assignment/list_assignment.html
{% extends "teachers/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/datatables.min.css'%}">
    
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}

{% block content %}

<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-sub-header">
                        <h3 class="page-title">Assignments</h3>
                        
                    </div>
                </div>
            </div>
        </div>

        <div class="student-group-form">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search by ID ...">
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search by Name ...">
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search by Phone ...">
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="search-student-btn">
                        <button type="btn" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table comman-shadow">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Assignments</h3>
                                </div>
                                <div class="col-auto text-end float-end ms-auto download-grp">
                                    <a href="students.html" class="btn btn-outline-gray me-2 active"><i
                                            class="feather-list"></i></a>
                                    <a href="students-grid.html" class="btn btn-outline-gray me-2"><i
                                            class="feather-grid"></i></a>
                                    <a href="#" class="btn btn-outline-primary me-2"><i
                                            class="fas fa-download"></i> Download</a>
                                    <a href="add-student.html" class="btn btn-primary"><i
                                            class="fas fa-plus"></i></a>
                                </div>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table
                                class="table border-0 star-student table-hover table-center mb-0 datatable table-striped">
                                <thead class="student-thread">
                                    <tr>
                                        <th>
                                            <div class="form-check check-tables">
                                                <input class="form-check-input" type="checkbox"
                                                    value="something">
                                            </div>
                                        </th>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Course</th>

                                        <th>Start</th>
                                        <th>End</th>
                                        <th class="text-end">Action</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for assignment in assignments %}
                                    <tr>
                                        <td>
                                            <div class="form-check check-tables">
                                                <input class="form-check-input" type="checkbox"
                                                    value="something">
                                            </div>
                                        </td>
                                        <td>{{assignment.id.hex|slice:":5" }}</td>
                                        <td>{{assignment.course }}</td>
                                        <td>
                            
                                            <a href="student-details.html">{{assignment.name}}</a>
                                           
                                        </td>
                                        <td>{{assignment.start}}</td>
                                        <td>{{assignment.end}}</td>
                                    
                                        <td class="text-end">
                                            <div class="actions ">
                                                
                                                <a href="{% url 'teacher:edit_assignment' assignment.id %}" class="btn btn-sm bg-danger-light">
                                                    <i class="feather-edit"></i>
                                                </a>
                                                <a href = "{% url 'teacher:delete_assignment' assignment.id %}" class="btn btn-sm bg-danger-light delete-btn">
                                                    <i class="feather-trash" ></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/feather.min.js'%}"></script>
    <script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
    <script src="{% static 'plugins/datatables/datatables.min.js'%}"></script>
    <script src="{% static 'js/script.js'%}"></script>
    
{% endblock script %}

templates/teachers/assignment/submitted_assignment.html
{% extends "teachers/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/datatables.min.css'%}">
    
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}

{% block content %}

<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-sub-header">
                        <h3 class="page-title">Submitted Assignments</h3>
                        
                    </div>
                </div>
            </div>
        </div>

        <div class="student-group-form">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search by ID ...">
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search by Name ...">
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search by Phone ...">
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="search-student-btn">
                        <button type="btn" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table comman-shadow">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Submitted Assignments</h3>
                                </div>
                                <div class="col-auto text-end float-end ms-auto download-grp">
                                    <a href="students.html" class="btn btn-outline-gray me-2 active"><i
                                            class="feather-list"></i></a>
                                    <a href="students-grid.html" class="btn btn-outline-gray me-2"><i
                                            class="feather-grid"></i></a>
                                    <a href="#" class="btn btn-outline-primary me-2"><i
                                            class="fas fa-download"></i> Download</a>
                                    <a href="add-student.html" class="btn btn-primary"><i
                                            class="fas fa-plus"></i></a>
                                </div>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table
                                class="table border-0 star-student table-hover table-center mb-0 datatable table-striped">
                                <thead class="student-thread">
                                    <tr>
                                        <th>
                                            <div class="form-check check-tables">
                                                <input class="form-check-input" type="checkbox"
                                                    value="something">
                                            </div>
                                        </th>
                                        <th>Student</th>
                                        <th>Grade</th>
                                        <th>Course</th>
                                        <th>Title</th>
                                        <th>Checked</th>
                                        
                                        <th class="text-end">Action</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for assignment in assignments %}
                                    <tr>
                                        <td>
                                            <div class="form-check check-tables">
                                                <input class="form-check-input" type="checkbox"
                                                    value="something">
                                            </div>
                                        </td>
                                        <td>{{assignment.student}}</td>
                                        <td>{{assignment.student.grade}}</td>
                                        <td>{{assignment.work.course.course_name}}</td>
                                        <td>{{assignment.work.name}}</td>
                                        <td> {% if assignment.checked %}
                                            <i class="feather-check-circle text-success"></i>
                                        {% else %}
                                            <i class="feather-x-circle text-danger"></i>
                                        {% endif %}</td>
                                       
                                    
                                        <td class="text-end">
                                            <div class="actions ">
                                                
                                                <a href="{% url 'teacher:submitted_assignment_detail' assignment.id %}" class="btn btn-sm bg-danger-light">
                                                    <i class="feather-edit"></i>
                                                </a>
                                               
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/feather.min.js'%}"></script>
    <script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
    <script src="{% static 'plugins/datatables/datatables.min.js'%}"></script>
    <script src="{% static 'js/script.js'%}"></script>
    
{% endblock script %}