chat/urls.py
from django.urls import path
from .views import *

app_name = "chat"

urlpatterns = [
    path("", ChatBoxView.as_view(), name="chat_box"),
    path("student/<uuid:pk>/chat", ChatMessageView.as_view(), name="chat_message"),
]

school_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


from accounts.views import *
from student.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
    path("parent/", include("parent.urls")),
    path("profile/", include("user_profile.urls")),
    path("chat/", include("chat.urls")),
    path("staff/",include("staff.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from .views import *

app_name = "staff"

urlpatterns = [
    path("dashboard/", StaffDashboardView.as_view(), name="staff_dashboard"),
    path("announcement/", AnnouncementView.as_view(), name="announcement"),
    path("event/", EventView.as_view(), name="event"),
    path("holiday/", HolidayView.as_view(), name="holiday"),
    path("gallery/", GalleryView.as_view(), name="gallery"),
    path("library/books/",libraryBookView.as_view(),name="librarybook"),
    path("library/borrowed/",BorrowedView.as_view(),name="borrowed"),
    path("library/addbook/",AddBook.as_view(),name="addbook"),
    path("library/lendbook/<str:b_id>/",LendBookView.as_view(),name="lendbook"),
    path("library/returnbook/<str:borrow_id>/",ReturnBook.as_view(),name="return"),
    path("transportation/alert/",AlertView.as_view(),name="alert"),
    path("transportation/alert/delete/<str:a_id>/",DeleteAlert.as_view(),name="delete_alert"),
    path("transportation/alert/edit/<str:a_id>/",EditAlertView.as_view(),name="edit_alert"),
    path("transportation/alert/add/",AddAlertView.as_view(),name="add_alert"),
    path("college/fee/",FeeView.as_view(),name="feelist"),
    path("college/fee/add/",AddFeeView.as_view(),name="add_fee"),
    path("college/payment/",PaymentView.as_view(),name="payment"),
    path("college/payment/add/",AddPaymentView.as_view(),name="add_payment"),
    path("exam/list/",ExamListView.as_view(),name="exam_list"),
    path("exam/add/",AddExamView.as_view(),name="add_exam"),
    path("exam/edit/<str:e_id>/",EditExamView.as_view(),name="edit_exam"),
]

staff/forms.py
from django import forms
from .models import Borrowing, libraryBook,Alert,Fee,Payment,Exam


class BorrowingForm(forms.ModelForm):
    class Meta:
        model = Borrowing
        fields = ["book", "borrowed_person"]
        labels = {
            "borrowed_person": "Borrowed Person",
        }
        required = {
            "borrowed_person": True,
        }

    def __init__(self, *args, **kwargs):
        book_id = kwargs.pop("book_id", None)
        super().__init__(*args, **kwargs)

        if book_id:
            self.fields["book"].initial = book_id
            self.fields["book"].widget = forms.HiddenInput()
            self.fields["book"].disabled = True
        self.fields["borrowed_person"].widget.attrs.update({"class": "form-control"})

    def clean_book(self):
        book_id = self.cleaned_data["book"]
        return book_id


class LibraryBookForm(forms.ModelForm):
    class Meta:
        model = libraryBook
        fields = ["name", "author"]
        labels = {
            "name": "Name",
            "author": "Author",
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "author": forms.TextInput(attrs={"class": "form-control"}),
        }
class AlertForm(forms.ModelForm):
    class Meta:
        model = Alert
        fields = '__all__'
        widgets = {
            'route': forms.Select(attrs={'class': 'form-control'}),
            'alert_type': forms.Select(attrs={'class': 'form-control'}),
            'alert_message': forms.Textarea(attrs={'class': 'form-control'}),
            'alert_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
        }
#college_fee_form
class FeeForm(forms.ModelForm):
    class Meta:
        model = Fee
        fields = '__all__'
        widgets = {
            'fee_name': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'due_date': forms.DateInput(attrs={'class': 'form-control','type':'date'}),
        }
class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = '__all__'
        widgets = {
            'student': forms.Select(attrs={'class': 'form-control'}),
            'fee': forms.Select(attrs={'class': 'form-control'}),
            'amount_paid': forms.NumberInput(attrs={'class': 'form-control'}),
            'payment_date': forms.DateInput(attrs={'class': 'form-control','type':'date'}),
        }
#exam
class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ['course', 'description', 'start_date', 'duration', 'status']
        widgets = {
            'course': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'start_date': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'duration':forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

staff/views.py
from datetime import date
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect,get_object_or_404
from django.views.generic import View
from .mixins import StaffRequiredMixin
from school_news.models import *
from gallery.models import *
from .models import libraryBook, Borrowing
from .forms import BorrowingForm, LibraryBookForm,AlertForm,FeeForm,PaymentForm,ExamForm
from .services import *


class StaffDashboardView(StaffRequiredMixin, View):
    template_name = "staffs/dashboard.html"

    def get(self, request, *args, **kwargs):
        available_books = LibraryService.get_total_available_books()
        overdue_books = LibraryService.get_total_overdue_books()
        added_books = LibraryService.get_recently_added_books()
        for i in added_books:
            print(i)
        context = {
            "available_books": available_books,
            "overdue_books": overdue_books,
            "added_books": added_books,
        }

        return render(request, self.template_name, context)


class AnnouncementView(StaffRequiredMixin, View):
    active_tab = "announcement"
    template_name = "staffs/news/announcement.html"

    def get(self, request, *args, **kwargs):
        announcements = Announcement.objects.all()
        context = {"active_tab": self.active_tab, "announcements": announcements}
        return render(request, self.template_name, context)


class EventView(StaffRequiredMixin, View):
    active_tab = "event"
    template_name = "staffs/news/events.html"

    def get(self, request, *args, **kwargs):
        events = Event.objects.all()
        context = {"active_tab": self.active_tab, "events": events}
        return render(request, self.template_name, context)


class HolidayView(StaffRequiredMixin, View):
    active_tab = "holiday"
    template_name = "staffs/news/holiday.html"

    def get(self, request, *args, **kwargs):
        holidays = Holiday.objects.all()
        context = {"active_tab": self.active_tab, "holidays": holidays}
        return render(request, self.template_name, context)


class GalleryView(StaffRequiredMixin, View):
    active_tab = "gallery"
    template_name = "staffs/gallery/gallery.html"

    def get(self, request):
        gallerys = Gallery.objects.all()
        context = {"active_tab": self.active_tab, "gallerys": gallerys}
        return render(request, self.template_name, context)


class libraryBookView(StaffRequiredMixin, View):
    active_tab = "librarybook"
    template_name = "staffs/library/booklist.html"

    def get(self, request):
        books = libraryBook.objects.all()
        context = {"active_tab": self.active_tab, "books": books}
        return render(request, self.template_name, context)

    def post(self, request):
        query = request.POST.get("bookquery")
        print(query)
        books = libraryBook.objects.filter(name__icontains=query)
        context = {"active_tab": self.active_tab, "books": books}
        return render(request, self.template_name, context)


class BorrowedView(StaffRequiredMixin, View):
    active_tab = "borrowed"
    template_name = "staffs/library/borrowedlist.html"

    def get(self, request):
        borrowlist = Borrowing.objects.all()
        context = {"active_tab": self.active_tab, "borrowlist": borrowlist}
        return render(request, self.template_name, context)


class LendBookView(StaffRequiredMixin, View):
    template_name = "staffs/library/lendbook.html"

    def get(self, request, b_id):
        form = BorrowingForm(book_id=b_id)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, b_id):
        form = BorrowingForm(request.POST, book_id=b_id)
        if form.is_valid():
            form.save()
            return redirect("staff:librarybook")
        context = {"form": form}
        return render(request, self.template_name, context)


class ReturnBook(StaffRequiredMixin, View):
    def get(self, request, borrow_id):
        try:
            Borrow = Borrowing.objects.get(id=borrow_id)
            Borrow.delete()
            return redirect("staff:librarybook")
        except:
            return redirect("staff:dashboard")


class AddBook(StaffRequiredMixin, View):
    active_tab = "addbook"
    template_name = "staffs/library/addbook.html"

    def get(self, request):
        form = LibraryBookForm()
        context = {"active_tab": self.active_tab, "form": form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = LibraryBookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("staff:librarybook")
        context = {"active_tab": self.active_tab, "form": form}
        return render(request, self.template_name, context)
class AlertView(StaffRequiredMixin, View):
    active_tab = "alert"
    template_name = "staffs/transportation/alert.html"

    def get(self, request):
        alerts = Alert.objects.all()
        context = {"active_tab": self.active_tab, "alerts": alerts}
        return render(request, self.template_name, context)
class DeleteAlert(StaffRequiredMixin,View):
    def get(self,request,a_id):
        try:
            alert=Alert.objects.get(id=a_id)
            alert.delete()
            return redirect("staff:alert")
        except:
            return redirect("staff:alert")
class EditAlertView(StaffRequiredMixin,View):
    active_tab = "alert"
    template_name = "staffs/transportation/edit_alert.html"
    def get(self,request,a_id):
        alert=get_object_or_404(Alert, id=a_id)
        form=AlertForm(instance=alert)
        context={
            "active_tab": self.active_tab,
            "form":form,
            "a_id":a_id,
        }
        return render(request,self.template_name,context)
    def post(self,request,a_id):
        alert=get_object_or_404(Alert, id=a_id)
        form=AlertForm(request.POST,instance=alert)
        if form.is_valid():
            form.save()
            return redirect("staff:alert")
        else:
            context={
            "active_tab": self.active_tab,
            "form":form,
            "a_id":a_id,
            }
            return render(request,self.template_name,context)
class AddAlertView(StaffRequiredMixin,View):
    active_tab = "alert"
    template_name = "staffs/transportation/add_alert.html"
    def get(self,request):
        form=AlertForm()
        context={
            "active_tab": self.active_tab,
            "form":form,
        }
        return render(request,self.template_name,context)
    def post(self,request):
        form=AlertForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("staff:alert")
        else:
            context={
            "active_tab": self.active_tab,
            "form":form,
            }
            return render(request,self.template_name,context)
#college fee
class FeeView(StaffRequiredMixin,View):
    active_tab = "fee"
    template_name = "staffs/college_fee/fee.html"
    def get(self,request):
        fees=Fee.objects.all()
        context={
            "active_tab": self.active_tab,
            "fees":fees
        }
        return render(request,self.template_name,context)
class PaymentView(StaffRequiredMixin,View):
    active_tab = "payment"
    template_name = "staffs/college_fee/payment_list.html"
    def get(self,request):
        payments=Payment.objects.all()
        context={
            "active_tab": self.active_tab,
            "payments":payments
        }
        return render(request,self.template_name,context)
class AddFeeView(StaffRequiredMixin,View):
    active_tab = "fee"
    template_name = "staffs/college_fee/add_fee.html"
    def get(self,request):
        form=FeeForm()
        context={
            "active_tab": self.active_tab,
            "form":form,   
        }
        return render(request,self.template_name,context)
    def post(self,request):
        form=FeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("staff:feelist")
        else:
            context={
            "active_tab": self.active_tab,
            "form":form,   
        }
        return render(request,self.template_name,context)
class AddPaymentView(StaffRequiredMixin,View):
    active_tab="payment"
    template_name = "staffs/college_fee/add_payment.html"
    def get(self,request):
        form=PaymentForm()
        context={
            "active_tab": self.active_tab,
            "form":form,   
        }
        return render(request,self.template_name,context)
    def post(self,request):
        form=PaymentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("staff:payment")
        else:
            context={
            "active_tab": self.active_tab,
            "form":form,   
        }
        return render(request,self.template_name,context)
#exam
class ExamListView(StaffRequiredMixin,View):
    active_tab="exam_list"
    template_name = "staffs/exam/exam_list.html"
    def get(self,request):
        exams=Exam.objects.all()
        context={
            "active_tab": self.active_tab,
            "exams":exams
        }
        return render(request,self.template_name,context)
class AddExamView(StaffRequiredMixin,View):
    active_tab="add_exam"
    template_name = "staffs/exam/add_exam.html"
    def get(self,request):
        form=ExamForm()
        context={
            "active_tab": self.active_tab,
            "form":form
        }
        return render(request,self.template_name,context)
    def post(self,request):
        form=ExamForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("staff:exam_list")
        else:
            context={
            "active_tab": self.active_tab,
            "form":form
            }

templates/staffs/college_fee/add_fee.html
{% extends "staffs/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
<link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
    rel="stylesheet">
<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
<link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}

{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Add Fee</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Add Fee</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Add Fee Form:</h3>
                                </div>
                            </div>
                        </div>
                        <form action="{% url 'staff:add_fee' %}" method="post">
                            {% csrf_token %}
                            {{form.as_p}}
                            <input type="submit" value="Add" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'js/feather.min.js'%}"></script>
<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/apexcharts.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/chart-data.js'%}"></script>
<script src="{% static 'js/script.js'%}"></script>
{% endblock script %}

templates/staffs/college_fee/add_payment.html
{% extends "staffs/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
<link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
    rel="stylesheet">
<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
<link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}

{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Add Payment</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Add Payment</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Add Payment Form:</h3>
                                </div>
                            </div>
                        </div>
                        <form action="{% url 'staff:add_payment' %}" method="post">
                            {% csrf_token %}
                            {{form.as_p}}
                            <input type="submit" value="Add" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'js/feather.min.js'%}"></script>
<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/apexcharts.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/chart-data.js'%}"></script>
<script src="{% static 'js/script.js'%}"></script>
{% endblock script %}

templates/staffs/college_fee/fee.html
{% extends "staffs/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
<link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
    rel="stylesheet">
<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
<link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}

{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Fee</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Fee</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Fee List:</h3>
                                </div>
                            </div>
                        </div>
                        {% if not fees %}
                        <p>Empty Fee</p>
                        {% else %}
                        <div class="table-responsive">
                            <table
                                class="table border-0 star-student table-hover table-center mb-0 table-striped">
                                <thead class="student-thread">
                                    <tr>
                                        <th>Name</th>
                                        <th>Amount</th>
                                        <th>Due Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for fee in fees %}
                                    <tr>
                                        <td>
                                            <h2>
                                                <a>{{fee.fee_name}}</a>
                                            </h2>
                                        </td>
                                        <td>{{fee.amount}}</td>
                                        <td>{{fee.due_date}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <a href="{% url 'staff:add_fee' %}"><button class="btn btn-primary mx-2">Add Fee</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'js/feather.min.js'%}"></script>
<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/apexcharts.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/chart-data.js'%}"></script>
<script src="{% static 'js/script.js'%}"></script>
{% endblock script %}

templates/staffs/college_fee/payment_list.html
{% extends "staffs/sidebar.html" %}
{% load static %}
{% block link %}
<link rel="shortcut icon" href="{% static 'media/img/favicon.png' %}">
<link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
    rel="stylesheet">
<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/feather/feather.css'%}">
<link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css'%}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock link %}

{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Payment</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Payment</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Payment List:</h3>
                                </div>
                            </div>
                        </div>
                        {% if not payments %}
                        <p>Empty payments</p>
                        {% else %}
                        <div class="table-responsive">
                            <table
                                class="table border-0 star-student table-hover table-center mb-0 table-striped">
                                <thead class="student-thread">
                                    <tr>
                                        <th>Student Name</th>
                                        <th>Fee</th>
                                        <th>Amount Paid</th>
                                        <th>Payment Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for payment in payments %}
                                    <tr>
                                        <td>
                                            <h2>
                                                <a>{{payment.student.name}}</a>
                                            </h2>
                                        </td>
                                        <td>{{payment.fee}}</td>
                                        <td>{{payment.amount_paid}}</td>
                                        <td>{{payment.payment_date}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <a href="{% url 'staff:add_payment' %}"><button class="btn btn-primary mx-2">Add Payment</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'js/feather.min.js'%}"></script>
<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/apexcharts.min.js'%}"></script>
<script src="{% static 'plugins/apexchart/chart-data.js'%}"></script>
<script src="{% static 'js/script.js'%}"></script>
{% endblock script %}